import {
  createContext, forwardRef, useCallback, useContext, useId, useMemo, useState,
} from 'react';
import type { ComponentPropsWithoutRef, CSSProperties, ReactNode } from 'react';
import * as stylex from '@stylexjs/stylex';
import { colors } from '../../tokens/colors.stylex';
import { radius } from '../../tokens/radius.stylex';
import { space } from '../../tokens/spacing.stylex';
import { text } from '../../tokens/typography.stylex';

export type PanelSize = 's' | 'm';

// Set once on <Panel>; header, title, body and footer read it so consumers
// configure everything (size, collapse) in one place instead of wiring props
// through the tree. The chevron toggle renders inside PanelHeader — the
// header is what remains visible when a panel is collapsed, and it works
// with any header content, title or not.
interface PanelContextValue {
  size: PanelSize;
  collapsible: boolean;
  collapsed: boolean;
  onToggle: () => void;
  // Generated by Panel; PanelTitle attaches it to its text so the toggle can
  // borrow the title as its accessible name (see the toggle's aria-labelledby).
  labelId: string;
}

const PanelContext = createContext<PanelContextValue>({
  size: 'm',
  collapsible: false,
  collapsed: false,
  onToggle: () => {},
  labelId: '',
});

// Fold motion, shared by the body/footer rows, the header divider and the
// chevron so the collapse reads as one gesture. User-initiated enter/exit →
// ease-out (quart); panels are section-sized, so the slow end of the
// 150–250ms UI band, with the exit ~20% faster so closing feels snappy.
// CSS picks the transition from the destination state, which is what makes
// the two directions differ — and makes the animation interruptible.
const foldEase = 'cubic-bezier(0.165, 0.84, 0.44, 1)';
const expandMs = '250ms';
const collapseMs = '200ms';

const styles = stylex.create({
  panel: {
    borderColor: colors.surfaceBorderSurface,
    borderRadius: radius.xl,
    borderStyle: 'solid',
    borderWidth: '1px',
    overflow: 'hidden',
    backgroundColor: colors.surfaceShade,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  header: {
    gap: space.px8,
    transition: {
      default: `border-bottom-color ${expandMs} ${foldEase}`,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    alignItems: 'center',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-between',
    paddingInlineEnd: space.px8,
    paddingInlineStart: space.px12,
    // Anchor for the absolutely-positioned collapse toggle.
    position: 'relative',
    borderBottomColor: colors.surfaceBorderSurface,
    borderBottomStyle: 'solid',
    // The divider only separates the header from content below it. When the
    // header is the last child (e.g. a collapsed panel) it would stack against
    // the Panel's own bottom border, reading as a doubled line — so drop it.
    borderBottomWidth: { default: '1px', ':last-child': '0' },
    borderTopLeftRadius: `calc(${radius.xl} - 1px)`,
    borderTopRightRadius: `calc(${radius.xl} - 1px)`,
  },
  // The toggle sits out of flow (see styles.toggle), so the header only has
  // to clear it with 6px of breathing room after the button box: the 20px S
  // box ends at 28, the 28px M box at 36. Consumer children stay direct flex
  // children — layout overrides via className keep working with no wrapper
  // in the way.
  headerCollapsibleS: {
    paddingInlineStart: '34px',
  },
  headerCollapsibleM: {
    paddingInlineStart: '42px',
  },
  // The state-driven twin of the :last-child rule above: while collapsed the
  // divider is gone no matter what stays mounted below the header — which is
  // now always the case, since the body folds instead of unmounting. The
  // divider fades via border-COLOR, never width: the header is border-box
  // sized, so an animated width would grow the content area 1px mid-fold and
  // jiggle the vertically-centered content, and fractional border widths
  // render as flicker. Color is paint-only — geometry never moves. The
  // invisible 1px border stays on the collapsed header; it sits against the
  // panel's own border and changes nothing visually.
  headerCollapsed: {
    transition: {
      default: `border-bottom-color ${collapseMs} ${foldEase}`,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    borderBottomColor: 'transparent',
  },
  // The collapse mechanism: a grid row transitioning 1fr ↔ 0fr folds any
  // content height with zero measurement JS. The outer div clips, the spacer
  // breaks the min-size chain (an fr track can't shrink below its item's
  // min-height, and consumer content may set one), and `visibility` — part
  // of the transition, so it flips only when the closing fold finishes —
  // removes hidden content from the a11y tree and tab order.
  fold: {
    overflow: 'hidden',
    transition: {
      default: `grid-template-rows ${expandMs} ${foldEase}, visibility ${expandMs}`,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    display: 'grid',
    gridTemplateRows: '1fr',
    visibility: 'visible',
  },
  foldCollapsed: {
    transition: {
      default: `grid-template-rows ${collapseMs} ${foldEase}, visibility ${collapseMs}`,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    gridTemplateRows: '0fr',
    visibility: 'hidden',
  },
  foldSpacer: {
    minHeight: 0,
  },
  // Total heights: s 44 = 8+28+8, m 56 = 10+36+10 (content row 28/36)
  headerS: {
    paddingBlock: space.px8,
    minHeight: '44px',
  },
  headerM: {
    paddingBlock: space.px10,
    minHeight: '56px',
  },
  title: {
    gap: space.px6,
    alignItems: 'center',
    color: colors.textSecondary,
    display: 'inline-flex',
    fontWeight: text.weightSemiBold,
  },
  titleS: {
    fontSize: text.sizeSmall,
    lineHeight: '12px',
  },
  titleM: {
    fontSize: text.sizeRegular,
    lineHeight: '20px',
  },
  toggle: {
    padding: 0,
    borderStyle: 'none',
    transition: {
      default: 'background-color 0.2s ease, scale 0.15s ease-out',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    alignItems: 'center',
    backgroundColor: { default: 'transparent', ':hover': colors.white5Hover },
    color: colors.textSecondary,
    cursor: 'pointer',
    display: 'inline-flex',
    // Out of flow so the header's space-between never counts it as a flex
    // item — content keeps its layout whether or not the panel is collapsible.
    // Vertically centered even when a wrapping title grows the header.
    insetInlineStart: '8px',
    justifyContent: 'center',
    position: 'absolute',
    scale: { default: '1', ':active': '0.96' },
    translate: '0 -50%',
    top: '50%',
    '::before': {
      content: '""',
      position: 'absolute',
    },
  },
  // The visible button (hover box) is 20×20 around the 14px chevron on S and
  // 28×28 around the 16px one on M, both anchored 8px from the panel edge
  // (see styles.toggle) so the box never crowds the corner. The radius scales
  // with the box (6px on 20, 8px on 28) to sit well inside the panel's 12px
  // corners, and the ::before insets extend the clickable area to 40×40 in
  // both cases.
  toggleS: {
    borderRadius: radius.medium,
    height: '20px',
    width: '20px',
    '::before': {
      inset: '-10px',
    },
  },
  toggleM: {
    borderRadius: radius.large,
    height: '28px',
    width: '28px',
    '::before': {
      inset: '-6px',
    },
  },
  // Paired with the fold — same easing and direction-aware durations, so the
  // rotation and the body collapsing read as one gesture.
  chevron: {
    transition: {
      default: `transform ${expandMs} ${foldEase}`,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  chevronCollapsed: {
    transition: {
      default: `transform ${collapseMs} ${foldEase}`,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    transform: 'rotate(-90deg)',
  },
  // One geometry regardless of panel size — Figma only specs the M case
  // (36px total = 4px block padding around 28px controls, 8px inline);
  // an S variant can be added when a design calls for one.
  footer: {
    gap: space.px8,
    paddingBlock: space.px4,
    paddingInline: space.px8,
    alignItems: 'center',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-between',
    borderTopColor: colors.surfaceBorderSurface,
    borderTopStyle: 'solid',
    borderTopWidth: '1px',
    minHeight: '36px',
  },
});

interface PanelSectionProps extends ComponentPropsWithoutRef<'div'> {
  children: ReactNode;
}

interface PanelTitleProps extends ComponentPropsWithoutRef<'span'> {
  children: ReactNode;
}

// Collapse comes in two flavors, and the union makes half-wired states
// unrepresentable (`collapsed` without `onToggle` is a compile error):
// - Uncontrolled (the common case): pass `collapsible` (or `defaultCollapsed`,
//   which implies it) and Panel owns the state — PanelBody hides itself.
// - Controlled (escape hatch): pass `collapsed` + `onToggle` together and the
//   consumer owns the state (persistence, expand-all, etc.).
interface UncontrolledCollapseProps {
  collapsible?: boolean;
  defaultCollapsed?: boolean;
  collapsed?: never;
  onToggle?: never;
}

interface ControlledCollapseProps {
  collapsed: boolean;
  onToggle: () => void;
  collapsible?: never;
  defaultCollapsed?: never;
}

// Omit the native onToggle (the <details> toggle event) — on Panel that name
// belongs to the collapse API.
type PanelRootProps = Omit<ComponentPropsWithoutRef<'div'>, 'onToggle'> & {
  children: ReactNode;
  size?: PanelSize;
} & (UncontrolledCollapseProps | ControlledCollapseProps);

// stylex.props() produces the atomic class list (and sometimes inline vars);
// fold the caller's className/style in after it so external overrides
// survive the merge.
const mergeExternal = (
  sx: ReturnType<typeof stylex.props>,
  className?: string,
  style?: CSSProperties,
) => ({
  ...sx,
  className: [sx.className, className].filter(Boolean).join(' '),
  ...(sx.style || style ? { style: { ...sx.style, ...style } } : null),
});

// Private to Panel — a visual detail of the component, not a public icon.
// Rendered with currentColor so it follows the toggle's token color.
// Default (expanded) points down; collapsed rotates to point right.
const Chevron = ({ size, collapsed }: { size: PanelSize; collapsed: boolean }) => {
  const px = size === 'm' ? 16 : 14;
  return (
    <svg
      width={px}
      height={px}
      viewBox="0 0 12 12"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      {...stylex.props(styles.chevron, collapsed && styles.chevronCollapsed)}
    >
      <path d="M9 5L6.09642 7.90358C6.04317 7.95683 5.95683 7.95683 5.90358 7.90358L3 5" stroke="currentColor" strokeLinecap="round" />
    </svg>

  );
};

export const Panel = forwardRef<HTMLDivElement, PanelRootProps>(({
  className,
  style,
  children,
  size = 'm',
  collapsible = false,
  defaultCollapsed,
  collapsed: controlledCollapsed,
  onToggle,
  ...rest
}, ref) => {
  const [ownCollapsed, setOwnCollapsed] = useState(defaultCollapsed ?? false);
  const toggleOwn = useCallback(() => setOwnCollapsed((c) => !c), []);
  const labelId = useId();

  const isControlled = controlledCollapsed !== undefined;
  const context = useMemo(() => ({
    size,
    collapsible: isControlled || collapsible || defaultCollapsed !== undefined,
    collapsed: isControlled ? controlledCollapsed : ownCollapsed,
    onToggle: onToggle ?? toggleOwn,
    labelId,
  }), [
    size, isControlled, collapsible, defaultCollapsed,
    controlledCollapsed, ownCollapsed, onToggle, toggleOwn, labelId,
  ]);

  return (
    <PanelContext.Provider value={context}>
      <div ref={ref} {...rest} {...mergeExternal(stylex.props(styles.panel), className, style)}>
        {children}
      </div>
    </PanelContext.Provider>
  );
});
Panel.displayName = 'Panel';

export const PanelHeader = forwardRef<HTMLDivElement, PanelSectionProps>(({
  className, style, children, ...rest
}, ref) => {
  const {
    size, collapsible, collapsed, onToggle, labelId,
  } = useContext(PanelContext);
  return (
    <div
      ref={ref}
      {...rest}
      {...mergeExternal(
        stylex.props(
          styles.header,
          size === 'm' ? styles.headerM : styles.headerS,
          collapsible && (size === 'm' ? styles.headerCollapsibleM : styles.headerCollapsibleS),
          collapsed && styles.headerCollapsed,
        ),
        className,
        style,
      )}
    >
      {collapsible && (
        // Named by the title text when a PanelTitle is present (labelledby
        // pointing at nothing is skipped), otherwise the aria-label fallback
        // applies — so title-less headers still get a usable name.
        <button
          type="button"
          aria-expanded={!collapsed}
          aria-label="Toggle panel"
          aria-labelledby={labelId}
          onClick={onToggle}
          {...stylex.props(styles.toggle, size === 'm' ? styles.toggleM : styles.toggleS)}
        >
          <Chevron size={size} collapsed={collapsed} />
        </button>
      )}
      {children}
    </div>
  );
});
PanelHeader.displayName = 'PanelHeader';

export const PanelTitle = forwardRef<HTMLSpanElement, PanelTitleProps>(({
  className, style, children, ...rest
}, ref) => {
  const { size, labelId } = useContext(PanelContext);
  return (
    <span
      ref={ref}
      {...rest}
      {...mergeExternal(
        stylex.props(styles.title, size === 'm' ? styles.titleM : styles.titleS),
        className,
        style,
      )}
    >
      {/* Labels the header toggle, so screen readers hear "Positions,
          collapsed" instead of the generic fallback name. */}
      <span id={labelId}>{children}</span>
    </span>
  );
});
PanelTitle.displayName = 'PanelTitle';

// Folds (rather than unmounts) while the panel is collapsed — see
// styles.fold for the mechanism. Content stays mounted, so child state
// (inputs, scroll positions) survives a collapse, like native <details>;
// content that must truly unmount can be conditionally rendered by the
// consumer in controlled mode. The consumer-facing div is the innermost
// one, so className/style/ref behave exactly as before the fold existed.
export const PanelBody = forwardRef<HTMLDivElement, PanelSectionProps>(({
  children, ...rest
}, ref) => {
  const { collapsed } = useContext(PanelContext);
  return (
    <div {...stylex.props(styles.fold, collapsed && styles.foldCollapsed)}>
      <div {...stylex.props(styles.foldSpacer)}>
        <div ref={ref} {...rest}>{children}</div>
      </div>
    </div>
  );
});
PanelBody.displayName = 'PanelBody';

export const PanelFooter = forwardRef<HTMLDivElement, PanelSectionProps>(({
  className, style, children, ...rest
}, ref) => {
  // A collapsed panel shows only its header — footer actions (pagination
  // etc.) operate on the hidden body, so the footer folds in sync with it.
  // Its top border rides on the inner content div, where the fold clips it
  // away only as the row closes completely.
  const { collapsed } = useContext(PanelContext);
  return (
    <div {...stylex.props(styles.fold, collapsed && styles.foldCollapsed)}>
      <div {...stylex.props(styles.foldSpacer)}>
        <div ref={ref} {...rest} {...mergeExternal(stylex.props(styles.footer), className, style)}>
          {children}
        </div>
      </div>
    </div>
  );
});
PanelFooter.displayName = 'PanelFooter';
